### ISSUE TITLE
PyMISP Custom object and CSV Import

### ISSUE THREAD

**Issue by phmazzoni** [MISP/PyMISP#714] opened 2021-03-04 19:08 UTC
Hi!

I have created a MISP Custom Object Template. For that, I have followed instructions on https://github.com/MISP/PyMISP/issues/477

The new object template is on the folders of MISP and PyMISP. After update, I can see the object template on the web ui.
Now I am trying to load events from a csv file, using the load_csv.py script.
When I run it, passing the name of the new object template (-n template-name), I got the following error:

Traceback (most recent call last):
  File "load_csv.py", line 65, in <module>
    objects = csv_loader.load()
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/csvloader.py", line 41, in load
    allowed_fieldnames = list(tmp_object._definition['attributes'].keys())
TypeError: 'NoneType' object is not subscriptable

Do you have any advice on it?

Thanks in advance,
Pedro

**Comment by Rafiot** [comment] 2021-03-04 19:40
You need the template locally on the machine you run the script.

The easiest way to do it is to add the template in the `PyMISP/pymisp/data/misp-objects/objects/<name>/definition.json`.

**Comment by chrisinmtown** [comment] 2021-03-04 19:49
It seems to me that csvloader.py at line 40 should check whether it was successful at loading an object from the template_name argument.  If that step fails there's little sense in continuing.

**Comment by Rafiot** [comment] 2021-03-04 19:56
yeah, I didn't think about custom objects in that context.

**Comment by phmazzoni** [comment] 2021-03-04 20:18
> You need the template locally on the machine you run the script.
> 
> The easiest way to do it is to add the template in the `PyMISP/pymisp/data/misp-objects/objects/<name>/definition.json`. Then, it should work out of the box.

Thanks!

But I have already done that.
The template is loaded on MISP and PyMISP, I have checked this. It also appears on the Web Ui.

Maybe PyMISP is not loading custom module names?

One more info, when I run the /pymisp/pymisp/data/misp-objects/tools/list_of_objects.py, I can see my template there.

**Comment by Rafiot** [comment] 2021-03-04 21:01
The fact it is on the web UI is not something you need to care about: you can push an object to a MISP instance and that instance does not know the template What is failing is that PyMISP doesn't find the template.

It is late here, and I won't solve the problem tonight, but just FYI, there is a working example there: https://github.com/MISP/PyMISP/blob/main/tests/testlive_comprehensive.py#L1662

In order for PyMISP to load the custom object templates, you need to install PyMISP from the repository in a virtual environment, preferably with poetry, and not system wide.

if you can do the following, the CSV loader should work: 

```python
from pymisp import MISPObject

mo = MISPObject("<objectname>")
```

**Comment by github-germ** [comment] 2021-03-04 21:17
Not sure this helps this situation; however, when we add a custom object, in addition to placing the `definition.json` as above in MISP and PyMISP dirs, we also run this command to load the object details into the database. 
```
/var/www/MISP/app/Console/cake Admin updateObjectTemplates 00
```

**Comment by Rafiot** [comment] 2021-03-04 22:51
it won't help. The problem is that the local PyMISP install doesn't find the template.

**Comment by phmazzoni** [comment] 2021-03-05 03:36
Thanks for all the support!
I will try that!
Actually, it is a Palo Alto custom object, I think this can help many people so I willing to contribute. 
This is MISP!

**Comment by Rafiot** [comment] 2021-03-05 09:05
Cool! if you add it in the misp-object repository and do a PR, it will be easier for everyone

**Comment by phmazzoni** [comment] 2021-03-05 14:48
Done!

https://github.com/MISP/misp-objects/pull/308

Thanks

**Comment by Rafiot** [comment] 2021-03-05 14:51
merged, and I bumped the submodule in PyMISP, you should have all you need now!

**Comment by phmazzoni** [comment] 2021-03-05 15:17
Thanks!

But same behavior here:

`./load_csv.py -n paloalto-threat-event -p panorama-misp.txt
Traceback (most recent call last):
  File "./load_csv.py", line 61, in <module>
    objects = csv_loader.load()
  File "/usr/local/lib/python3.6/dist-packages/pymisp/tools/csvloader.py", line 41, in load
    allowed_fieldnames = list(tmp_object._definition['attributes'].keys())
TypeError: 'NoneType' object is not subscriptable
`

Can you please try to reproduce it?

Thanks,
Pedro

**Comment by phmazzoni** [comment] 2021-03-05 16:03
One more info, one I dumped the object, I got:

obj._load_template = <bound method MISPObject._load_template of <MISPObject(name=paloalto-threat-event)>
obj._load_template_path = <bound method MISPObject._load_template_path of <MISPObject(name=paloalto-threat-event)>
obj._remove_from_not_jsonable = <bound method AbstractMISP._remove_from_not_jsonable of <MISPObject(name=paloalto-threat-event)>
obj._set_default = <bound method MISPObject._set_default of <MISPObject(name=paloalto-threat-event)>
obj._set_tags = <bound method AbstractMISP._set_tags of <MISPObject(name=paloalto-threat-event)>
obj._set_template = <bound method MISPObject._set_template of <MISPObject(name=paloalto-threat-event)>
obj._standalone = True
obj._strict = False
obj._to_feed = <bound method MISPObject._to_feed of <MISPObject(name=paloalto-threat-event)>
obj._validate = <bound method MISPObject._validate of <MISPObject(name=paloalto-threat-event)>
obj.add_attribute = <bound method MISPObject.add_attribute of <MISPObject(name=paloalto-threat-event)>
obj.add_attributes = <bound method MISPObject.add_attributes of <MISPObject(name=paloalto-threat-event)>
obj.add_reference = <bound method MISPObject.add_reference of <MISPObject(name=paloalto-threat-event)>

**Comment by Rafiot** [comment] 2021-03-05 16:35
Right, the name of the directory is not the same as the name of the template, sorry, I missed it when merging. We need to rename the directory from `panorama` to `paloalto-threat-event`

**Comment by phmazzoni** [comment] 2021-03-05 16:46
OK! I'll do that!

Thanks!

**Comment by phmazzoni** [comment] 2021-03-05 17:12
https://github.com/MISP/misp-objects/pull/309

**Comment by phmazzoni** [comment] 2021-03-05 17:39
I have notice that pymisp was looking for objects in the following directory:

obj.misp_objects_path = PosixPath('/usr/local/lib/python3.6/dist-packages/pymisp/data/misp-objects/objects')

I have copied the object to that path, and now:

obj.description = 'Palo Alto Threat log Event'
obj.disable_validation = None
obj.distribution = 5
obj.edited = True
obj.force_misp_objects_path_custom = <bound method MISPObject.force_misp_objects_path_custom of <MISPObject(name=paloalto-threat-event)>
obj.from_dict = <bound method MISPObject.from_dict of <MISPObject(name=paloalto-threat-event)>
obj.from_json = <bound method AbstractMISP.from_json of <MISPObject(name=paloalto-threat-event)>
obj.get = <bound method Mapping.get of <MISPObject(name=paloalto-threat-event)>
obj.get_attributes_by_relation = <bound method MISPObject.get_attributes_by_relation of <MISPObject(name=paloalto-threat-event)>
obj.has_attributes_by_relation = <bound method MISPObject.has_attributes_by_relation of <MISPObject(name=paloalto-threat-event)>
obj.items = <bound method Mapping.items of <MISPObject(name=paloalto-threat-event)>
obj.jsonable = <bound method AbstractMISP.jsonable of <MISPObject(name=paloalto-threat-event)>
obj.keys = <bound method Mapping.keys of <MISPObject(name=paloalto-threat-event)>
obj.meta-category = 'network'
obj.misp_objects_path = PosixPath('/usr/local/lib/python3.6/dist-packages/pymisp/data/misp-objects/objects')
obj.name = 'paloalto-threat-event'
obj.pop = <bound method MutableMapping.pop of <MISPObject(name=paloalto-threat-event)>
obj.popitem = <bound method MutableMapping.popitem of <MISPObject(name=paloalto-threat-event)>
obj.references = []
obj.resources_path = PosixPath('/usr/local/lib/python3.6/dist-packages/pymisp/data')
obj.set_not_jsonable = <bound method AbstractMISP.set_not_jsonable of <MISPObject(name=paloalto-threat-event)>
obj.setdefault = <bound method MutableMapping.setdefault of <MISPObject(name=paloalto-threat-event)>
obj.sharing_group_id = 0
obj.standalone = True
obj.template_uuid = 'e6fa7a87-1173-43d6-86c2-b4d02af5fc74'
obj.template_version = 4
obj.to_dict = <bound method MISPObject.to_dict of <MISPObject(name=paloalto-threat-event)>
obj.to_json = <bound method MISPObject.to_json of <MISPObject(name=paloalto-threat-event)>
obj.update = <bound method MutableMapping.update of <MISPObject(name=paloalto-threat-event)>
obj.update_not_jsonable = <bound method AbstractMISP.update_not_jsonable of <MISPObject(name=paloalto-threat-event)>
obj.uuid = '93d29666-1eac-42b2-830d-ec3e0887bd77'
obj.values = <bound method Mapping.values of <MISPObject(name=paloalto-threat-event)>
Traceback (most recent call last):
  File "./load_csv.py", line 85, in <module>
    new_object = misp.add_object(args.update_event, o, pythonify=True)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 545, in add_object
    event_id = get_uuid_or_id_from_abstract_misp(event)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 66, in get_uuid_or_id_from_abstract_misp
    if 'uuid' in obj:  # type: ignore

**Comment by phmazzoni** [comment] 2021-03-05 17:54
It worked! I forgot to pass -i to create a event! 
Thanks for all the support!

**Comment by Rafiot** [comment] 2021-03-05 18:06
Excellent! Thank you for your patience.

**Closed by Rafiot** 2021-03-05 18:06 UTC
Labels: T: bug

**Comment by chrisinmtown** [comment] 2021-03-05 18:23
please double-check this @Rafiot I thought you were going to add a check in the code, csvloader.py at line 40

**Comment by Rafiot** [comment] 2021-03-05 18:33
You're right, done.
