### ISSUE TITLE
Unable to integrate a MISP instance with Microsoft Sentinel

### ISSUE THREAD

**Issue by OldToys** [MISP/PyMISP#841] opened 2022-06-27 20:38 UTC
I acquired access to CIRCL's MISP instance and I need to integrate with my SIEM solution (Microsoft Sentinel). I followed the steps described here https://www.circl.lu/doc/misp/connectors/ but I am running into an issue with I run the script.py file.
My config.py file has misp_verifymycert = false. I also set my MISP API key to only accept requests from certain public IPs.
Another thing to note is that I am running the script form a a WSL Linux box running on my laptop as a test. Once I get this to work, I will most likely dedicate a Virtual Machine for this process.
 
The error I am still getting is:

![image](https://user-images.githubusercontent.com/25939712/176031483-90c936db-aac0-49d3-840f-e7ef64fc8e06.png)

**Comment by righel** [comment] 2022-06-28 07:21
Hello @OldToys 
Seems to be two problems:
1. Your `misp_domain` setting seems to be incorrect, please check your `config.py` file, seems there's a trailing `/attributes` in the value, the value should be `https://misppriv.circl.lu`
2. Your API key seems to be incorrect or do not have the proper permissions, could you please from your WSL Linux box running the following curl request and share the results? Please replace `YOUR_AUTH_KEY` with the same API key you are using for the Sentinel script.
    ```console
    curl --insecure --location --request GET 'https://misppriv.circl.lu/users/view/me' \
    --header 'Accept: application/json' \
    --header 'Authorization: YOUR_AUTH_KEY'
    ```
   If the request returns a json object representing a user, please share the `Role` that's returned.

Let me know if that helps.

**Comment by righel** [comment] 2022-06-29 06:35
Could you share the relevant bits of your `/var/www/MISP/app/tmp/logs/error.log` located in your MISP instance?

**Comment by righel** [comment] 2022-06-30 07:55
> This is not my MISP instance. I don't host it. I was just given access to this after I requested it. https://www.circl.lu/services/misp-malware-information-sharing-platform/

Sorry for the confusion, indeed those are in the remote instance.

> Well never mind, I just checked WSL and saw this error:
> 
> ![image](https://user-images.githubusercontent.com/25939712/176219383-fa7f72e3-8e57-4af0-bf49-0315c5ccead0.png)

I just checked the query that returned 500 error and the issue is there is no pagination implemented in the script you are using.
* See: https://github.com/microsoftgraph/security-api-solutions/blob/master/Samples/MISP/script.py

The MISP API request as such will try to fetch ALL the instance events, this will make the request either timeout or exceed the memory limit. You should fetch pages with a reasonable size by using pagination.

Other users seem to be having the same issue:
* https://github.com/microsoftgraph/security-api-solutions/issues/108

I'd suggest to either modify the script to implement pagination or open an issue in the [microsoftgraph](https://github.com/microsoftgraph/security-api-solutions) repository.
However, if you plan such intense/automated usage of a remote private MISP instance, I would recommend you to set up your own MISP instance and connect it via the pull sync mechanism, and then connect your Microsoft Sentinel to your own MISP instance.  

I'll close the issue as it's not PyMISP / MISP related anymore.
Hope this helps.

**Closed by righel** 2022-06-30 07:55 UTC

**Comment by OldToys** [comment] 2022-07-05 20:28
Closing the loop on this one. I was able to make some progress after using the Filter in the config file.
However, now I am getting this:

![image](https://user-images.githubusercontent.com/25939712/177410730-7f50de9e-fd5f-4588-aa63-91cdbb946ba8.png)

and one of the logs files include this:

![image](https://user-images.githubusercontent.com/25939712/177410762-8349c6e9-7abd-409c-bc9d-dba5cc0f8e7c.png)
