### ISSUE TITLE
small issue in examples/del.py with delete attribute argument

### ISSUE THREAD

**Issue by ananth-she11z** [MISP/PyMISP#662] opened 2020-11-21 01:36 UTC
Under examples/del.py the following code snippet needs to be modified as follows to work for deleting attribute (deleting event works fine though)

""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if args.event:
        result = misp.delete_event(args.event)
    else:
        result = misp.delete_attribute(args.attribute)

""""""""""""""""""""""""""""""""""""""""""""""""""""""""   
In above code "args.attribute" which parse attribute ID like "misp.delete_attribute(4578545)" fails as per current code
ERROR [api.py:2961 - _check_response() ] Something went wrong (404): {'name': 'Invalid attribute', 'message': 'Invalid attribute', 'url': '/attributes/delete/4578545'}

FIX:

Set it to pass HARD DELETE which MISP expects and it works well:
Replace it to "misp.delete_attribute(str(args.attribute/1))" >>>> misp.delete_attribute(str(4578545/1))

Above change works well!

**Comment by ananth-she11z** [comment] 2020-11-21 06:02
FYI - I made it work through using the following way

attr_id = str(attr. id) + '/1'
misp.delete_attribute(str(attr_id))

**Comment by chrisinmtown** [comment] 2020-11-21 13:43
It would really help if you post a small self-contained code example to create the event, add the attribute and delete the attribute.  If it helps, I can post code that successfully uses the delete_attribute function with just an ID (integer) argument.

**Comment by chrisinmtown** [comment] 2020-11-23 12:45
I tested examples/del.py and cannot reproduce this problem.  I used a script to create an event in my MISP instance and add an attribute to the event.  Then I took the attribute id, updated examples/keys.py with the local url and auth key, and ran del.py.  The result:
```
(py36) me@vpn:~/git/github/MISP.PyMISP/examples% python3 del.py -a 134458908
{'message': 'Attribute deleted.'}
```

**Comment by Rafiot** [comment] 2020-11-23 12:48
@chrisinmtown thank you for testing, the issue was in fact confusing.

@ananth-she11z: Could it be you're running `delete_attribute` after you ran `delete_event`?

**Comment by ananth-she11z** [comment] 2020-11-23 19:52
Hi Team,

Thanks for the support, unfortunately I am also not able to generate same issue again for some reason and once I used the old script which was giving those errors, everything works fine now. I suspect the reason to be that in my script I have implemented to take attribute name itself like 'www.example.com' from user which is queried in MISP DB to get attribute ID from DB which is then passed to misp.delete_attribute method, I guess there might be some issue there. But allover the method in pymisp looks ok to me now. Though as I don't want to use this method to get attribute ID, is there any way in pymisp that it takes attribute value1 as argument to delete an attribute? if yes, this will help by not doing a scripted query in DB to get ID.

Thanks!
Ananth

**Comment by Rafiot** [comment] 2020-11-24 12:19
No, you need to pass either a `MISPAttribute`, an attribute ID or UUID to the delete method, not the value itself.

I don't think it's your plan, but I strongly discourage you to directly delete an attribute in the database without using the API (or the UI), as it bypasses the ACLs and will cause unexpected issues down the line.

**Comment by chrisinmtown** [comment] 2020-11-24 12:55
I suggest closing this issue.

**Closed** 2020-11-24 13:44 UTC
Labels: S: diagnosed, T: support, help wanted
