### ISSUE TITLE
get_event pythonify is slow

### ISSUE THREAD

**Issue by imidoriya** [MISP/PyMISP#661] opened 2020-11-20 21:22 UTC
Running some regular jobs and I found a big amount of my time was spent on `get_event(pythonify=True)`, which I thought was strange. `get_event(pythonify=False)` was very fast.  I tried to isolate the issue, but didn't have much luck as I was dealing in production (hope spend more time in a dev environment).  What I ended up doing was a search for the id instead.

So instead of this:
`self.client.get_event(event_id, pythonify=True)`
I did this which was really fast.
`self.client.search(eventid=event_id, limit=1, include_event_tags=True, with_attachments=False, pythonify=True)[0]`

I know this probably isn't very helpful at the moment, but I thought I would at least report it.

**Comment by Rafiot** [comment] 2020-11-20 21:42
Unless I'm mistaken, the only difference is the attachment. Does the event you're fetching has attachment(s)? Because pythonify is both cases does the same thing.

**Comment by imidoriya** [comment] 2020-11-20 22:14
Yes, it does have an attachment.

**Comment by Rafiot** [comment] 2020-11-20 22:52
I'm curious: is it a big attachment? Just wondering if what is slow is downloading the attachment, or loading it in PyMISP.

@MISP/developers is there a feature to skip the attachments on GET event?

**Comment by chrisinmtown** [comment] 2020-11-21 13:36
It would help if you quantify fast/slow with time in seconds, also the size of the attachment in bytes.  I believe the cost of converting just one single Event dict to a MISPEvent object in memory on the client side should be trivial.

**Comment by Rafiot** [comment] 2020-11-21 16:50
I wouldn't say it is trivial (there is quite a bit of massaging and conversion of types happening), but it should not be excessively long.

**Comment by imidoriya** [comment] 2020-11-22 05:52
Not particularly large size.. average malware samples. But you are correct, after testing it is clearly the attachment causing the large delay.
get_event - approx 10-11 seconds
search w/Attachment - approx 10-12 seconds
search w/o Attachment - .06 seconds

**Comment by imidoriya** [comment] 2020-11-22 06:07
In my quick test above, which was just a random event coming in, the size of the file in bytes was 5525504.

I had high disk usage Friday, which probably contributed to my delay at the time if it has to pull the attachment from disk vs everything else likely being in database cache, in addition to the size of the data that must be returned across the wire.

So yeah, I think it would be highly beneficial to have the option to exclude things like attachments that could cause a good bit of overhead.

**Comment by Rafiot** [comment] 2020-11-22 12:06
Thank you for the diagnostic, we will sort it out!

**Comment by imidoriya** [comment] 2020-11-22 16:51
To add to the initial thought, pythonify does appear to play a part in the response time for get_event().  To add to the diagnostic, running `get_event(pythonify=False)` returns much quicker.  So maybe it's not the disk time, but adding the attachment to the object?  The search seems to give little penalty to pythonify.  Anyway.. I found it strange.

| command | time in seconds |
| :-- | :-: |
| get_event(pythonify=False) | 0.1678 |
| get_event(pythonify=True) | 11.126 |
| search(pythonify=True, with_attachments=True) | 12.138 |
| search(pythonify=False, with_attachments=True) | 11.669 |
| search(pythonify=True, with_attachments=False) | 0.066 |
| search(pythonify=False, with_attachments=False) | 0.042 |

**Comment by Rafiot** [comment] 2020-11-22 17:09
okay, so that's super weird, because `get_event(pythonify=False)` and `search(pythonify=False, with_attachments=True)` should be the same... 

I'll investigate that.

**Comment by Rafiot** [comment] 2020-11-24 11:58
I wasn't able to reproduce the 10x difference between `search(pythonify=False, with_attachments=False)` and `search(pythonify=False, with_attachments=True)`, nor between `get_event(pythonify=True)` and `search(pythonify=False, with_attachments=True)`

Note that I run the test locally, so the network overhead will be minimal.

Is there any chance you can share the event/code you're using, please?

**Comment by mokaddem** [comment] 2020-11-25 07:23
> @MISP/developers is there a feature to skip the attachments on GET event?

GET on `/events/view/[id]/includeAttachments:1` now supports the `includeAttachments` flag

**Comment by imidoriya** [comment] 2020-11-25 13:33
@Rafiot My code was a wrapper for getting an event, often times just supplying the event_id.
```py
    def get_event(self, event, refresh=None):
        if isinstance(event, dict):
            if "Event" in event:
                event = event["Event"]
            if "event_id" in event:
                return self.client.get_event(event.get("event_id"), pythonify=True)
            elif "id" in event:
                return self.client.get_event(event.get("id"), pythonify=True)
        elif isinstance(event, str) or isinstance(event, int):
            return self.client.get_event(int(event), pythonify=True)
        elif isinstance(event, MISPEvent) and refresh:
            try:
                return self.client.get_event(event.id, pythonify=True)
            except:
                logging.info("Error Reading Event: %s" % event.to_json())
        return event
```
### Testing
For testing, I adding some timing checks and ran the various commands.
```py
   def get_event(self, event, force=None, pythonify=True, with_attachments=False):
        if isinstance(event, dict):
            if "Event" in event:
                event = event["Event"]
            if "event_id" in event:
                return self.search_event(event.get("event_id"), pythonify=pythonify, with_attachments=with_attachments)
            elif "id" in event:
                return self.search_event(event.get("id"), pythonify=pythonify, with_attachments=with_attachments)
        elif isinstance(event, str) or isinstance(event, int):
            import time
            logging.info(int(event))
            start = time.time()
            self.client.get_event(int(event), pythonify=False)
            logging.info("ge pyf " + str(time.time()-start))

            start = time.time()
            self.search_event(int(event), pythonify=False, with_attachments=False)
            logging.info("sr pyf waf " + str(time.time()-start))
            
            start = time.time()
            self.search_event(int(event), pythonify=False, with_attachments=True)
            logging.info("sr pyf wat " + str(time.time()-start))

            start = time.time()
            self.client.get_event(int(event), pythonify=True)
            logging.info("ge pyt " + str(time.time()-start))

            start = time.time()
            self.search_event(int(event), pythonify=True, with_attachments=True)
            logging.info("sr pyt wat " + str(time.time()-start))

            start = time.time()
            self.search_event(int(event), pythonify=True, with_attachments=False)
            logging.info("sr pyt waf " + str(time.time()-start))

            return self.search_event(int(event), pythonify=pythonify, with_attachments=with_attachments)
        elif isinstance(event, MISPEvent) and force:
            try:
                return self.search_event(event.id, pythonify=pythonify, with_attachments=with_attachments)
            except:
                logging.info("Error Reading Event: %s" % event.to_json())
        return event
```

**Comment by Rafiot** [comment] 2020-11-25 13:39
Okay, and what is `self.search_event`?

**Comment by imidoriya** [comment] 2020-11-25 13:46
Oh yeah, sorry.. 
```py
    def search_event(self, event_id, pythonify, with_attachments):
        event = self.client.search(
            controller="events", eventid=event_id, limit=1, with_attachments=with_attachments, include_event_tags=True, pythonify=True
        )
        if len(event) > 0:
            return event[0]
        else:
            logging.info("Failed to find Event ID: %s" % event_id)
            return None
```

**Comment by imidoriya** [comment] 2020-11-25 13:47
I see my error there... pythonify was always True.  That at least explains one of the confusing points.

**Comment by Rafiot** [comment] 2020-11-25 13:49
Right, so the **slow** calls are the ones with `pythonify=True`? Just making sure, because that would make more sense.

**Comment by imidoriya** [comment] 2020-11-25 14:04
It looks like the delay is when both pythonify and attachments are `True`. Here is another run using a smaller zipped file and fixing the pythonify in search.  I expect the 2x vs 10x is due to the file type/size and my disk / cpu usage at the time.

| command | time in seconds |
| :-- | :-: |
| get_event(pythonify=False) | 0.069 |
| get_event(pythonify=True) | 1.689 |
| search(pythonify=True, with_attachments=True) | 1.644 |
| search(pythonify=False, with_attachments=True) | 0.051 |
| search(pythonify=True, with_attachments=False) | 0.050 |
| search(pythonify=False, with_attachments=False) | 0.040 |

**Comment by Rafiot** [comment] 2020-11-25 14:11
Hmmm right, it is a little bit weird.

The file you get from the MISP instance is the base64 representation of the zipped & encrypted file you uploaded. `pythonify=True` will de-base64, de-crypt and unzip the file (all in memory), so I expect it to take a bit of time... 

I'll give it a try, thank you for the sample and the work you put in debugging!

**Comment by imidoriya** [comment] 2020-11-25 14:12
Happy I can help.  To upload the file into MISP, I'm following your example in [add_file_object.py](https://github.com/MISP/PyMISP/blob/main/examples/add_file_object.py)

**Comment by Rafiot** [comment] 2020-11-26 10:20
Oh wow, this is very interesting: I can reproduce the delay with zip files, but not with an exe file for example.

**Comment by Rafiot** [comment] 2020-11-26 12:32
This commit should solve your problems: https://github.com/MISP/PyMISP/commit/fe91e10cedb4660b58dcc0db7833c46a5b0efeb9

It will be part of the next release of PyMISP.

**Closed** 2020-11-30 22:10 UTC
Labels: S: diagnosed, T: support

**Comment by imidoriya** [comment] 2020-11-30 22:27
Interesting that you were using zipfile.  I was using that a while back to decrypt the attribute.get("data"), but I ran into problems where it failed to decrypt.  MISP was using AES encryption for the zip, so started using `AESZipFile` from pyzipper and that resolved my issues.  It appears they've changed that on Oct 21. 
 https://github.com/MISP/MISP/commit/44c688d551b568b07fa9f645225ed51f4e4f3e84#diff-eb515aeba4fd371030b9f12dfbc19915b5158f0123af4f0f4bc72b597dac1cf4

**Comment by Rafiot** [comment] 2020-11-30 22:57
wow, right, so it seems that `ZipArchive` is not in the default install guide, and if it was installed, the samples were breaking PyMISP.

That would explain why I never had the problem.

**Comment by imidoriya** [comment] 2020-12-01 16:20
@Rafiot, [mokaddem mentioned ](https://github.com/MISP/PyMISP/issues/661#issuecomment-733518918) that "GET on `/events/view/[id]/includeAttachments:1` now supports the `includeAttachments` flag".  Will this allow you to add it as an option to get_event() and would it still be relevant given your update?  I think your change applies to just pythonify correct?   I have had instances of filling up my logs / screen by me printing out the event on an error or something, so it could still be useful to have that option.  But just not sure how it work best.. it could be confusing to have includeAttachments=True option and then exclude it when you pythonify.   We have the distinction between malware-sample and other attachments.

**Comment by Rafiot** [comment] 2020-12-01 17:08
I want to add `includeAttachments:1` in the future (big attachments take time to download, and if the user doesn't need them, there is no reason for them to be there), but I need to come with a somewhat generic approach so all the calls can accept these kind of parameters by default, so it will take a bit more time. It shouldn't be a problem for pythonify, as I'll just discard the attributes with attachments.

**Comment by imidoriya** [comment] 2020-12-02 21:41
With the AES Zips, I assume you'll only be able to unzip the newer archives (or the really old ones).  All the ones done prior to the Oct change will still be AES encrypted.
