### ISSUE TITLE
Bug: search_index: EventTag has different formats

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#739] opened 2021-05-05 10:50 UTC
Found bug in PyMISP 2.4.142

The EventTag is sometimes a list, sometimes a dict. Just for different event, I get different type.

```
rsp1 = misp.search_index(eventid=1283212)
rsp2 = misp.search_index(eventid=570397)

>>> type(rsp1[0]['EventTag'])
<class 'dict'>
>>> type(rsp2[0]['EventTag'])
<class 'list'>

>>> rsp1[0]['EventTag'].keys()
dict_keys(['0', '1', '2', '3', '4', '6', '7', '8'])
>>> len(rsp2[0]['EventTag'])
2
```

I can provide more info if needed

Thanks!

**Comment by Rafiot** [comment] 2021-05-05 10:58
Just making sure: you're not enabling `pythonify` globally, right? Knowing that will help me figuring out where the issue is happening.

**Comment by sustefil** [comment] 2021-05-05 11:07
Hi.

No, this example above is just starting interactive Python3, importing pymisp, connecting to MISP instance and then search_index

**Comment by Rafiot** [comment] 2021-05-05 11:18
Ok, so you're receiving directly what MISP sends back, it's not modified by PyMISP.

@mokaddem @iglocska @JakubOnderka : I think the `EventTag` is returning the list of tags in a broken way, where the dict is turned in a dict or something like that.

**Comment by iglocska** [comment] 2021-05-05 11:37
Yep that sounds like a bug. This happens when an arbitrary index gets removed from the list and it's not reindexed (non exportable tag?)

**Comment by sustefil** [comment] 2021-05-12 07:35
Should I create an issue in the MISP project then? Thanks

**Comment by mokaddem** [comment] 2021-05-21 08:20
Fixed in https://github.com/MISP/MISP/commit/15a836b393fd42a610d398cbdf271b3c3d713d6f
Thanks for the report!

**Closed by mokaddem** 2021-05-21 08:20 UTC
