### ISSUE TITLE
Import STIX1 via PyMisp

### ISSUE THREAD

**Issue by ancailliau** [MISP/PyMISP#780] opened 2021-08-24 09:25 UTC
Importing a STIX file via the WebUI works but importing the same file via pymisp fails. 

```
    misp = init(misp_url, misp_key)

    for path in args.file:
        print("Importing " + str(path) + " file to MISP...")
        response = misp.upload_stix(path,version='1')
        print(response.text)
```

I get a 
```
<?xml version="1.0" encoding="UTF-8"?>
<response><saved>0</saved><name>Could not upload_stix Event</name><message>Could not upload_stix Event</message><url>/events/upload_stix</url><errors>Issues while loading the stix file. Please  check whether the dependencies for STIX are met via the diagnostic tool.</errors></response>
```

but all dependencies are OK and the import works in the web UI. I cannot find more details in the logs, sadly, except that the query reach the server that refuse it.

```
[24/Aug/2021:09:19:12 +0000] "POST /events/upload_stix HTTP/1.1" 403 1228 "-" "PyMISP 2.4.148 - Python 3.8"
```

Both the instance and pysmisp are up to date (and same for the python libs)

I'm not sure it is related to #704 since stix1 and stix2 are handled by different libraries.

**Comment by Rafiot** [comment] 2021-08-24 09:37
Hmm so in theory, it should work too, as all the processing is made on MISP side, and PyMISP just POST a blob of text. 

Just making sure of one thing: the same file you're pushing on the API worked from the web UI? If that's the case, the issue is probably that the content sent by PyMISP is broken and I'll look at that.

**Comment by ancailliau** [comment] 2021-08-24 09:43
From the size, it looks about right though. 
```
[24/Aug/2021:09:40:40 +0000] "POST /events/upload_stix HTTP/1.1" 302 1298 "REDACTED/events/upload_stix" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
````

**Comment by Rafiot** [comment] 2021-08-24 09:47
The method isn't doing anything with the document: https://github.com/MISP/PyMISP/blob/main/pymisp/api.py#L3011
So if it works on the web UI but not with the API, it's because the API does something wrong. I'm investigating.

**Comment by ancailliau** [comment] 2021-08-24 09:49
So we could/should close the issue here and move to http://github.com/misp/misp ?

**Comment by Rafiot** [comment] 2021-08-24 09:51
The same file works fine on the web UI, right? If it does work on the web UI, it means PyMISP is the issue and you're in the right project.

**Comment by ancailliau** [comment] 2021-08-24 10:03
Yes, same file work. Unless MISP does voodoo with referer or user-agent, it is indeed an issue here.

**Comment by Rafiot** [comment] 2021-08-24 11:35
Okay, so I think the problem is that the STIX file you're uploading is already on MISP (same UUID is already there). 

One way to check that is to delete the event **and** remove the UUID of the event from the blocklist.

**Comment by ancailliau** [comment] 2021-08-24 17:01
I deleted the event before testing and tested first before trying via the web UI. So I don't think the problem is there. I will double check and update here if different. Thanks for the help!

**Comment by Rafiot** [comment] 2021-08-24 17:02
If you delete the event but don't remove the UUID from the blacklist, re-uploading won't work.

**Comment by ancailliau** [comment] 2021-08-24 17:05
Ok, I will test tomorrow. But re-uploading via the web interface works.

**Comment by Rafiot** [comment] 2021-08-24 17:06
Okay, then, I have no idea. Maybe @chrisr3d will know more about it.

**Comment by ancailliau** [comment] 2021-09-09 11:25
@Rafiot I was able to dig a bit deeper on the issue. Apparently, the script `stix2misp.py` server side raise on exception while calling `STIXPackage.from_xml(filename)` (see https://github.com/MISP/MISP/blob/2.4/app/files/scripts/stix2misp.py#L1518). The error I get is `Input is not proper UTF-8, indicate encoding !`.

**Comment by ancailliau** [comment] 2021-09-09 12:15
For the record, the culprit file contains the following char: ©

```<stix:STIX_Package [...]>
    <stix:STIX_Header>
        <stix:Title>[...]</stix:Title>
        <stix:Description>[...]</stix:Description>
        <stix:Handling>
            <marking:Marking>
                <marking:Controlled_Structure>//node()</marking:Controlled_Structure>
                marking:Marking_Structure xsi:type='simpleMarking:SimpleMarkingStructureType'>
                    <simpleMarking:Statement>© YADA YADA</simpleMarking:Statement>
                </marking:Marking_Structure>
[...]
```

**Comment by Rafiot** [comment] 2021-09-09 15:01
Due to: https://github.com/psf/requests/issues/5560

Fixed by: https://github.com/MISP/PyMISP/commit/253730759ad218e3aaa33363982402b5990f17eb

**Closed by Rafiot** 2021-09-09 15:01 UTC
