### ISSUE TITLE
examples/add_file_object.py does not upload malware written in perl or bash

### ISSUE THREAD

**Issue by haegardev** [MISP/PyMISP#193] opened 2018-02-21 08:53 UTC
When add_file_object.py is used to upload a malware sample written in bash, it is not uploaded and no feedback is given to the user. An info message would be great.

Example:
./add_file_object.py  -p 'stage1.dat' -e 8494

**Comment by Rafiot** [comment] 2018-02-23 10:25
I'm not able to reproduce the bug: the bash files are properly uploaded (when I'm using the current master branch). 

Can you share a file that fails?

**Comment by Rafiot** [comment] 2018-05-30 13:18
Closing, please reopen if you stil have the problem.

**Closed by Rafiot** 2018-05-30 13:18 UTC
